More debugging

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -76,14 +76,12 @@ jobs:
           echo "Package name: $PKG_NAME"
           echo "Package version: $PKG_VERSION"
           echo "Checking if version exists on PyPI..."
-          HTTP_CODE=$(curl -s -o pypi.json -w "%{http_code}" https://pypi.org/pypi/$PKG_NAME/json)
-          if [ "$HTTP_CODE" = "200" ]; then
-            EXISTS=$(grep -F "\"$PKG_VERSION\"" pypi.json)
-            if [ -n "$EXISTS" ]; then
-              echo "Error: Version $PKG_VERSION of $PKG_NAME already exists on PyPI." >&2
-              sleep 1
-              exit 1
-            fi
+          EXISTS=$(curl -s https://pypi.org/pypi/$PKG_NAME/json | grep -F "\"$PKG_VERSION\"")
+          echo "$EXISTS comes out"
+          if [ -n "$EXISTS" ]; then
+            echo "Error: Version $PKG_VERSION of $PKG_NAME already exists on PyPI." >&2
+            sleep 1
+            exit 1
           fi
 
       - name: Publish release distributions to PyPI
